version: "3.9"
services:
  discordgpt:
    image: nekogravitycat/discordgpt:latest
    container_name: discordgpt
    restart: on-failure
    environment:
      - TZ=Asia/Taipei
    env_file:
      - ./.env/discordgpt.env
    volumes:
      - ./log:/app/log
